In [1]:
import pandas as pd

# Login using e.g. `huggingface-cli login` to access this dataset
df = pd.read_csv("hf://datasets/MOZNLP/MOZ-Smishing/test.csv")

In [2]:
df.columns = ["id", "fonte", "texto","classe"]
df

,id,fonte,texto,classe
0,1_0,sms,"Oi, peço para transferir aquele valor para meu...",Legitimate
1,2_0,sms,Bom dia babe..tudo bem? Não se esqueça de liga...,Legitimate
2,3_0,sms,AEN8AFWXJHC Confirmado. Compraste 19.00MT de ...,Legitimate
3,4_0,sms,"7GD04E51YZM. Caro Cliente, o codigo para efect...",Legitimate
4,5_0,sms,Bom dia babe. Está bem. Vou comprar.\nBoa viagem,Legitimate
...,...,...,...,...
2556,618_1,sms,"Bom,dia desculpe pesso mandar aquele valor par...",Smishing
2557,619_1,sms,"ok, ovalor nao podes mandar para aquele nr,por...",Smishing
2558,621_1,sms,"Boa Noite, O Valor Envia Nesse Nr: 848527898 O...",Smishing
2559,622_1,sms,"Ok, o valor podes enviar neste numero 25694049...",Smishing
2560,623_1,sms,O Valor Peo Pra Mandar Me Neste Nr. M-Pesa:857...,Smishing

In [3]:
df.info

<bound method DataFrame.info of          id fonte                                              texto  \
0       1_0   sms  Oi, peço para transferir aquele valor para meu...
1       2_0   sms  Bom dia babe..tudo bem? Não se esqueça de liga...
2       3_0   sms  AEN8AFWXJHC Confirmado. Compraste  19.00MT de ...
3       4_0   sms  7GD04E51YZM. Caro Cliente, o codigo para efect...
4       5_0   sms   Bom dia babe. Está bem. Vou comprar.\nBoa viagem
...     ...   ...                                                ...
2556  618_1   sms  Bom,dia desculpe pesso mandar aquele valor par...
2557  619_1   sms  ok, ovalor nao podes mandar para aquele nr,por...
2558  621_1   sms  Boa Noite, O Valor Envia Nesse Nr: 848527898 O...
2559  622_1   sms  Ok, o valor podes enviar neste numero 25694049...
2560  623_1   sms  O Valor Peo Pra Mandar Me Neste Nr. M-Pesa:857...

          classe
0     Legitimate
1     Legitimate
2     Legitimate
3     Legitimate
4     Legitimate
...          ...
2556    Smishing
2557    Smishing
2558    Smishing
2559    Smishing
2560    Smishing

[2561 rows x 4 columns]>

In [4]:
df.isnull().sum()

id        0
fonte     0
texto     0
classe    0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
# Mostra todos os valores únicos da coluna classe
df['classe'].unique()

array(['Legitimate', 'Smishing'], dtype=object)

In [7]:
# Conta a frequência de cada classe
df['classe'].value_counts()

classe
Legitimate    2009
Smishing       552
Name: count, dtype: int64

In [8]:
# Mostra todos os valores únicos da coluna fonte
df['fonte'].unique()

array(['sms', 'fb'], dtype=object)

In [9]:
# Conta a frequência de cada classe
df['fonte'].value_counts()

fonte
sms    2161
fb      400
Name: count, dtype: int64

In [10]:
# Troca o "\n" que ficou digitado errado (como texto) por um espaço em branco
df['texto'] = df['texto'].str.replace(r'\\n', ' ', regex=True)

In [11]:
# Troca espaços duplicados/triplicados por um espaço só, e remove espaços do início/fim da frase
df['texto'] = df['texto'].str.replace(r'\s+', ' ', regex=True).str.strip()

In [12]:
df

,id,fonte,texto,classe
0,1_0,sms,"Oi, peço para transferir aquele valor para meu...",Legitimate
1,2_0,sms,Bom dia babe..tudo bem? Não se esqueça de liga...,Legitimate
2,3_0,sms,AEN8AFWXJHC Confirmado. Compraste 19.00MT de c...,Legitimate
3,4_0,sms,"7GD04E51YZM. Caro Cliente, o codigo para efect...",Legitimate
4,5_0,sms,Bom dia babe. Está bem. Vou comprar. Boa viagem,Legitimate
...,...,...,...,...
2556,618_1,sms,"Bom,dia desculpe pesso mandar aquele valor par...",Smishing
2557,619_1,sms,"ok, ovalor nao podes mandar para aquele nr,por...",Smishing
2558,621_1,sms,"Boa Noite, O Valor Envia Nesse Nr: 848527898 O...",Smishing
2559,622_1,sms,"Ok, o valor podes enviar neste numero 25694049...",Smishing
2560,623_1,sms,O Valor Peo Pra Mandar Me Neste Nr. M-Pesa:857...,Smishing

In [13]:
#Criar coluna nova com o tamanho de cada texto
df['tam_texto'] = df['texto'].str.len()

In [14]:
# Mostra um resumo estatístico
df['tam_texto'].describe()

count    2561.000000
mean      102.255759
std        53.967747
min         5.000000
25%        61.000000
50%        93.000000
75%       145.000000
max       477.000000
Name: tam_texto, dtype: float64

In [15]:
# Mostra as linhas onde o texto tem menos de 5 caracteres
df[df['tam_texto'] < 5]

Empty DataFrame
Columns: [id, fonte, texto, classe, tam_texto]
Index: []

In [16]:
# Procura mensagens com sinais de erro de codificação
df[df['texto'].str.contains('Ã|â€|Â', regex=True, na=False)]

,id,fonte,texto,classe,tam_texto
2094,89_1,sms,Está ai o Número da M-pesa ou ponto24; valor m...,Smishing,102
2183,183_1,sms,"Bom_dia, O valor manda para este nr 851598083 ...",Smishing,95
2441,477_1,sms,O VALOR NÃO MANDA NAQUELE NUMERO MANDA NESTE N...,Smishing,131
2462,505_1,sms,O VALOR NÃO MANDA NAQUELE NUMERO MANDA NESTE N...,Smishing,126
2543,601_1,sms,O VALOR NÃO MANDA NAQUELE NUMERO MANDA NESTE N...,Smishing,119

In [17]:
# Mostra o texto completo das linhas suspeitas da mensagens com sinais de erro de codificação
for texto in df[df['texto'].str.contains('Ã|â€|Â', regex=True, na=False)]['texto']:
    print(texto)
    print('---')

Está ai o Número da M-pesa ou ponto24; valor manda neste nr 858814307 Vem Nome de FATIMA J JOÃo ARGOLA
---
Bom_dia, O valor manda para este nr 851598083 nome da confirmação M_pesa vem CLARA JORΔÃO GAIA.
---
O VALOR NÃO MANDA NAQUELE NUMERO MANDA NESTE Nr 857530074 MANDA NA CONTA MOVEL OU NA M-PESA VEM EM NOME DE ELISa N ARMANDO JOSSIAS.
---
O VALOR NÃO MANDA NAQUELE NUMERO MANDA NESTE Nr 857389236 MANDA NA CONTA MOVEL OU NA M-PESA VEM EM NOME DE VIRGINIA JOSE SAIDE
---
O VALOR NÃO MANDA NAQUELE NUMERO MANDA NESTE Nr 858050631 MANDA NA CONTA MOVEL OU NA M-PESA VEM EM NOME DE MIGUEL JOSE.
---

In [18]:
# Corrige a letra grega Δ que apareceu por engano no lugar do D
df['texto'] = df['texto'].str.replace('Δ', 'D', regex=False)

In [19]:
for texto in df[df['texto'].str.contains('Ã|â€|Â', regex=True, na=False)]['texto']:
    print(texto)
    print('---')

Está ai o Número da M-pesa ou ponto24; valor manda neste nr 858814307 Vem Nome de FATIMA J JOÃo ARGOLA
---
Bom_dia, O valor manda para este nr 851598083 nome da confirmação M_pesa vem CLARA JORDÃO GAIA.
---
O VALOR NÃO MANDA NAQUELE NUMERO MANDA NESTE Nr 857530074 MANDA NA CONTA MOVEL OU NA M-PESA VEM EM NOME DE ELISa N ARMANDO JOSSIAS.
---
O VALOR NÃO MANDA NAQUELE NUMERO MANDA NESTE Nr 857389236 MANDA NA CONTA MOVEL OU NA M-PESA VEM EM NOME DE VIRGINIA JOSE SAIDE
---
O VALOR NÃO MANDA NAQUELE NUMERO MANDA NESTE Nr 858050631 MANDA NA CONTA MOVEL OU NA M-PESA VEM EM NOME DE MIGUEL JOSE.
---

In [20]:
import re
# Procura caracteres que não sejam letras (com acento), números, pontuação comum ou espaço
padrao = r'[^a-zA-ZÀ-ÿ0-9\s.,!?;:()\-_/@*#%\'"]'
df[df['texto'].str.contains(padrao, regex=True, na=False)]

,id,fonte,texto,classe,tam_texto
22,23_0,sms,Babe vi sua mensagem...desculpa por te chamar ...,Legitimate,61
200,201_0,sms,Boa tarde babe. Deseju-te o mesmo😘 Com juizo,Legitimate,44
224,226_0,sms,Oi babe tudo bem? Sonhei contigo...beijei sua ...,Legitimate,109
235,237_0,sms,Millennium mobile O seu numero +258875725200 r...,Legitimate,121
245,247_0,sms,Babe....ishhhhh Dinheiro não bastou...gastei a...,Legitimate,130
...,...,...,...,...,...
2486,529_1,sms,"Boa Tarde, Aquela Conta Tem Problemas, Podes T...",Smishing,126
2509,560_1,sms,"Boa- Tarde, O inheiro Transfere Para Este Nr\ ...",Smishing,91
2525,582_1,sms,"Transferir, Para Este Nr\ 843490832, Ou Conta ...",Smishing,99
2549,608_1,sms,Aquele Valor Podes Mandar Nesta Conta M-pesa O...,Smishing,110
2559,622_1,sms,"Ok, o valor podes enviar neste numero 25694049...",Smishing,110

In [21]:
df[df['texto'].str.contains(r'[^a-zA-ZÀ-ÿ0-9\s.,!?;:()\-_/@*#%\'"]', regex=True, na=False)]['texto'].head(15)

22     Babe vi sua mensagem...desculpa por te chamar ...
200         Boa tarde babe. Deseju-te o mesmo😘 Com juizo
224    Oi babe tudo bem? Sonhei contigo...beijei sua ...
235    Millennium mobile O seu numero +258875725200 r...
245    Babe....ishhhhh Dinheiro não bastou...gastei a...
295    Bom Dia Mussa! FALA MAIS das 00:01 ate as 12:0...
311    Millennium mobile Digite *181# i IZI, i mais f...
389    enviar o valor para este numero (+84545455) no...
411    Eu sei que foste tu...😁 obrigada babe. Escreve...
422    GANHA ate 20 MINUTOS + 500 MEGAS ao receber di...
443    Bom dia babe...é hoje 😁 eu também fico muito f...
445    MBIM informa: Nas ultimas 24 h o seu cartao *0...
446    Devias ver o meu sorriso😁Boa tarde babe... tam...
468    MBIM informa: Nas ultimas 24 h o seu cartao *7...
503    Babe...gostaria de ir ao salão...paga pra mim!!?😉
Name: texto, dtype: object

In [22]:
df[df['texto'].str.contains(r'\\(?!n)', regex=True, na=False)]

,id,fonte,texto,classe,tam_texto
2242,246_1,sms,"Tai O Nr\840561775, Tem M-Pesa E Ponto24. Esta...",Smishing,76
2509,560_1,sms,"Boa- Tarde, O inheiro Transfere Para Este Nr\ ...",Smishing,91
2525,582_1,sms,"Transferir, Para Este Nr\ 843490832, Ou Conta ...",Smishing,99

In [23]:
# Remove barras invertidas soltas e troca por espaço
df['texto'] = df['texto'].str.replace(r'\\', ' ', regex=True)

In [24]:
# Normaliza espaços duplicados que podem ter sobrado depois da troca
df['texto'] = df['texto'].str.replace(r'\s+', ' ', regex=True).str.strip()

In [25]:
df[df['texto'].str.contains(r'\\', regex=True, na=False)]

Empty DataFrame
Columns: [id, fonte, texto, classe, tam_texto]
Index: []

In [26]:
# Mostra 10 textos aleatórios pra conferência visual
df['texto'].sample(10, random_state=1)

1395    Boa tarde tio tudo bem,tua pedir 700 mts quero...
2489    boa tarde o valor envia nesta conta m_pesa 855...
425     8E85632M3IV. Caro Cliente, o codigo para efect...
1654            Estudo dodo significado das coisas per se
1710    n kero flr d joana. s n vou flr sena k dpx pos...
280     Confirmado 7FB9483TA4V. Recebeste 1,000.00MT d...
587     7FA847X4J56 confirmado. Recebeste o pagamento ...
1884    simmm pk n tenho direit n posso ,isso te incom...
306     Confirmado 8F5968PB8SX. O teu saldo M-Pesa e 8...
891     Caro Cliente, em breve a tua conta atingira o ...
Name: texto, dtype: object

In [27]:
df.to_csv('dataset_limpo.csv', index=False)